In [2]:
import pandas as pd
import numpy as np

In [3]:
# Pandas version

pd.__version__

'2.2.3'

In [27]:
# Q1

df = pd.read_csv('car_fuel_efficiency_2026.csv')
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [ ]:
# Q2

print(df.shape)
print(f'Number of records in dataset: {df.shape[0]}')

(10000, 11)
Number of records in dataset: 10000

In [ ]:
# Q3

print(f'Number of fuel types presented in the dataset: {df['fuel_type'].nunique()}')

Number of fuel types presented in the dataset: 3

In [15]:
# Q4

print('Missing values by column:')
print(df.isnull().sum())

print(f'\nNumber of columns with missing values: {df.isnull().any().sum()}')

Missing values by column:
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

Number of columns with missing values: 2

In [21]:
# Q5

print(df['origin'].unique())
print(f"Maximum fuel efficiency (MPG) of cars from Asia: {df[df['origin'] == 'Asia']['fuel_efficiency_mpg'].max()}")
# df.loc[df['origin'] == 'Asia', 'fuel_efficiency_mpg'].max()

['Europe' 'Asia' 'USA']
Maximum fuel efficiency (MPG) of cars from Asia: 41.2

In [28]:
# Q6

# Median value of `horsepower` column
median_horsepower = df['horsepower'].median()

# Most frequent value of `horsepower` column
mode_horsepower = df['horsepower'].mode()[0]

# Fill missing values in `horsepower` column with the most frequent value
df['horsepower'] = df['horsepower'].fillna(mode_horsepower)

# New median
median_horsepower_after = df['horsepower'].median()

print(f'Median horsepower before filling with most frequent value: {median_horsepower}')
print(f'After filling: {median_horsepower_after}')

Median horsepower before filling with most frequent value: 254.0
After filling: 252.0

In [36]:
# Q7

# First 7 values of the columns `vehicle_weight` and `model_year` for cars from Asia
X_df = df[df['origin'] == 'Asia'][['vehicle_weight', 'model_year']].head(7)
display(X_df)

# Convert it to NumPy array
X = X_df.to_numpy()
print(X)

XTX = X.T.dot(X)
XTX_inv = np.linalg.inv(XTX)

y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

w = XTX_inv.dot(X.T).dot(y)
print(w)

print(f'Sum of the elements in the resulting weight vector: {w.sum()}')

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

[[4240 1996]
 [4310 1992]
 [4230 1997]
 [4420 1978]
 [3950 2007]
 [4750 2021]
 [4450 2019]]
[0.13644777 0.2327492 ]
Sum of the elements in the resulting weight vector: 0.36919696904925486